services:
  action-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: action-server
    volumes:
      - type: bind
        source: ./devdata
        target: /action-server/actions/devdata
        is_directory: true
      - action-server-data:/action-server/datadir
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SERVICE_FQDN_ACTION_SERVER_8087
    depends_on:
      - actual-finance
    labels:
      - traefik.http.middlewares.action-auth.basicauth.users=${TRAEFIK_AUTH_USER}

  actual-finance:
    build:
      context: ./actual-finance-agent
      dockerfile: Dockerfile
    container_name: actual-finance
    volumes:
      - type: bind
        source: ./actual-finance-agent/datadir
        target: /app/datadir
        is_directory: true
    restart: unless-stopped
    environment:
      - ACTUAL_PASSWORD=${SERVICE_PASSWORD_ACTUAL}
      - FILE_PASSWORD=${SERVICE_PASSWORD_FILE}
