services:
  action-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: action-server
    volumes:
      - type: bind
        source: ./devdata
        target: /action-server/actions/devdata
        is_directory: true
      - action-server-data:/action-server/datadir
    restart: unless-stopped

    depends_on:
      - actual-finance


  actual-finance:
    build:
      context: ./actual-finance-agent
      dockerfile: Dockerfile
    container_name: actual-finance
    volumes:
      - type: bind
        source: ./actual-finance-agent/datadir
        target: /app/datadir
        is_directory: true
    restart: unless-stopped
    environment:
      - ACTUAL_PASSWORD=${SERVICE_PASSWORD_ACTUAL}
      - FILE_PASSWORD=${SERVICE_PASSWORD_FILE}
