name: home-lab-actions
services:
  action-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:8087"  # Exposes Nginx, which now routes "/" to the web UI
    volumes:
      - ./devdata:/action-server/actions/devdata
      - action-server-data:/action-server/datadir
    restart: unless-stopped


  actual-finance:
    build:
      context: ./actual-finance-agent
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./actual-finance-agent/datadir:/app/datadir
    restart: unless-stopped
    environment:
      - ACTUAL_PASSWORD=${ACTUAL_PASSWORD}
      - FILE_PASSWORD=${FILE_PASSWORD}

volumes:
  action-server-data:
