name: actual-finance-system
services:
  action-server:

    image: ghcr.io/joshyorko/actual-finance-action-server:latest
    container_name: action-server

    volumes:
      - type: bind
        source: ./devdata
        target: /action-server/actions/devdata
        is_directory: true
      - action-server-data:/action-server/datadir
    restart: unless-stopped
    ports:
      - "8087:8087" 
    environment:
      - SERVICE_FQDN_ACTION_SERVER_8087
    depends_on:
      - actual-finance

  actual-finance:

    image: ghcr.io/joshyorko/actual-finance-agent:latest
    container_name: actual-finance

    volumes:
      - type: bind
        source: ./actual-finance-agent/datadir
        target: /app/datadir
        is_directory: true
    restart: unless-stopped
    environment:
      - ACTUAL_PASSWORD=${SERVICE_PASSWORD_ACTUAL}
      - FILE_PASSWORD=${SERVICE_PASSWORD_FILE}

volumes:
  action-server-data:
