apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: action-server
  name: action-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: action-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: action-server
    spec:
      containers:
        - image: ghcr.io/joshyorko/actual-finance-action-server:latest
          name: action-server
          ports:
            - containerPort: 8087
              protocol: TCP
          volumeMounts:
            - mountPath: /action-server/actions/devdata
              name: action-server-claim0
            - mountPath: /action-server/datadir
              name: action-server-data
      restartPolicy: Always
      volumes:
        - name: action-server-claim0
          persistentVolumeClaim:
            claimName: action-server-claim0
        - name: action-server-data
          persistentVolumeClaim:
            claimName: action-server-data
