apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: actual-finance
  name: actual-finance
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: actual-finance
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: actual-finance
    spec:
      containers:
        - env:
            - name: ACTUAL_PASSWORD
            - name: FILE_PASSWORD
          image: ghcr.io/joshyorko/actual-finance-agent:latest
          name: actual-finance
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/datadir
              name: actual-finance-claim0
      restartPolicy: Always
      volumes:
        - name: actual-finance-claim0
          persistentVolumeClaim:
            claimName: actual-finance-claim0
